CREATE DATABASE burgers_db; 
USE burgers_db; 

CREATE TABLE burgers (
	id INT NOT NULL AUTO_INCREMENT,

	burger_name VARCHAR (45) NULL,
	devoured BOOLEAN DEFAULT NULL,
	time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,


	PRIMARY KEY (id)
);